name       : python-aiofiles
version    : 22.1.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/a/aiofiles/aiofiles-22.1.0.tar.gz : 9107f1ca0b2a5553987a94a3c9959fe5b491fdf731389aa5b7b1bd0733e32de6
homepage   : https://github.com/Tinche/aiofiles
license    : Apache-2.0
component  : programming.python
summary    : File support for asyncio
description: |
    aiofiles is a library, for handling local disk files in asyncio applications.
build      : |
    %python3_setup
install    : |
    %python3_install
